### ISSUE TITLE
Fallback?

### ISSUE THREAD

**Issue by tylercollier** [khoaofgod/phpfastcache#67]
Does the fallback concept work? It doesn't for me. I just get an exception that says "Can't use this driver for your website!" when I try to use memcached with a fallback of files.

Here's my code.

```
$options = array(
	'fallback' => array(
		'memcached' => 'files'
	)
);
$cache = $cache = new phpFastCache('memcached', $options);
```

But looking through the phpfastcache code, I don't see any exception catching. Searching for the word fallback seems to result in almost nothing. It doesn't look like it could work.

**Comment by khoaofgod** [comment]
It work like this:
"memcached"  => "files",
"apc"       => "files"

Then, if you use phpfastcache as memcached, or apc , AND YOUR SERVER HAVE PROBLEM WITH THESE 2 , THEN it will use "files" instead of these 2.

This option is use for someone who switching / moving their website to new server, and they can not install memcached or apc right now, so they use fallback while installing memcached / apc.

However, you can set cache::auto or change the driver memcached to files, and switch back to memcached when u done with ur server.

Next week the version 2.4 will be release on Monday, and right now I am thinking about keep this fallback or not for the Monday Release.

**Comment by tylercollier** [comment]
I understand the idea. Where does the actual fallback happen? Where in the code?

**Comment by khoaofgod** [comment]
right now it simple on phpFastCache -> function __construct

**Comment by tylercollier** [comment]
```
if(isset(self::$config['fallback'][$storage])) {
    $storage = self::$config['fallback'][$storage];
}
```

It doesn't read from `$option` at all. That code looks like it ALWAYS uses the fallback, if there is a global fallback set.

**Comment by khoaofgod** [comment]
Look like only that section have that code, it's no use right now, it just a "ALIAS" , I think.

ok, I decide will improve it with a function called cache_check to make it work like my logic:
if memcached server failed then files cache will be use automatic until memcache server is BACK.

It's will be done on this monday's release.
